### PR TITLE
Add service and action file extensions

### PR DESCRIPTION
**Pull request by augustelalande**
Add service and action file extensions (.srv and .action) to enable highlighting for their corresponding interfaces.

### CODE REVIEW

**Review by Binpord — APPROVED** [review]
LGTM :)

Thanks for taking care of this, haven't used the extension in a while

**Comment by augustelalande** [comment]
No problem. I use it myself, so I appreciate you taking the time to publish it.

Would you mind publishing the update to packagecontrol?

**Comment by Binpord** [comment]
Whoops. Sorry, haven't used this in a while and kind of expected it to happen automatically based on the commit. Will take a look later today :)

**Comment by Binpord** [comment]
Done 👍

**Pull request merged**
